### ISSUE TITLE
Akward `<bb>` Parts

### ISSUE THREAD

**Issue by weilbith** [jszakmeister/markdown2ctags#13]
Hey there!
Thanks for implementing this! I choose this over the default tags, cause the supported nesting (as I heard).
My problem is, that I get some weird output in my _TagBar_. It seems like the subsections get splitted but, then the "main nodes" in _TagBar_ look something like this, for a depth of H4:
```
Header<bb>Sub-Header<bb>Sub-Sub-Header:
  - Sub-Sub-Sub-Header
  - Sub-Sub-Sub-Header

Header<bb>Sub-Header<bb>Sub-Sub-Header:
  - Sub-Sub-Sub-Header
```

That does not help much. I guess the `<bb>` should open a new line? Unfortunately they don't break in _Vim_ and I can't see much, since my _TagBar_ isn't thaaat wide.

**Comment by jszakmeister** [comment]
Do you have a document I can try?  And how do you have TagBar configured?  I've never seen anything like this! 🤔

**Comment by weilbith** [comment]
Just take this as example:
```markdown
# Header

## Sub-Header

### Sub-Sub-Header

#### Sub-Sub-Header

#### Sub-Sub-Header

### Sub-Sub-Header

# Header

## Sub-Header

```

I've just copy-pasted the configuration object from the README. :man_shrugging: 
This is how _TagBar_ looks with this example at my _Vim_:
![1544196346](https://user-images.githubusercontent.com/12543647/49656259-3097bd80-fa3d-11e8-80e4-1ece2416b348.jpg)

**Comment by jszakmeister** [comment]
Interesting.  I get:

![jszakmeisters-tagbar](https://user-images.githubusercontent.com/448087/49656485-79368300-fa0b-11e8-80d5-a08ff16f0b37.png)

Can you try running markdown2ctags directly:

```text
:: ./markdown2ctags.py -f - --sort=yes --sro=» example.md
!_TAG_FILE_FORMAT	2
!_TAG_FILE_SORTED	1
Header	example.md	/^# Header$/;"	s	line:1
Header	example.md	/^# Header$/;"	s	line:25
Sub-Header	example.md	/^## Sub-Header$/;"	s	line:29	section:Header
Sub-Header	example.md	/^## Sub-Header$/;"	s	line:5	section:Header
Sub-Sub-Header	example.md	/^### Sub-Sub-Header$/;"	s	line:21	section:Header»Sub-Header
Sub-Sub-Header	example.md	/^### Sub-Sub-Header$/;"	s	line:9	section:Header»Sub-Header
Sub-Sub-Header	example.md	/^#### Sub-Sub-Header$/;"	s	line:13	section:Header»Sub-Header»Sub-Sub-Header
Sub-Sub-Header	example.md	/^#### Sub-Sub-Header$/;"	s	line:17	section:Header»Sub-Header»Sub-Sub-Header
```

Also, do you use a non-utf8 encoding in Vim?   My guess is maybe your font can't handle the "»" character (which gets encoded as `\xc2\xbb\x0a`).  I used to suggest the standard pipe symbol (`|`), but that was a problem in some environments that used pipes in their headers.  If it's not a problem for you, change the `--sro` to `|` in the tagbar config for markdown and I think you'll be good.

**Comment by weilbith** [comment]
This is my output. Seems to look most likely identic. Guess our auto formatting just adds some more blank lines.

```sh
!_TAG_FILE_FORMAT       2
!_TAG_FILE_SORTED       1
Header  /tmp/test.md    /^# Header$/;"  s       line:1
Header  /tmp/test.md    /^# Header$/;"  s       line:13
Sub-Header      /tmp/test.md    /^## Sub-Header$/;"     s       line:15 section:Header
Sub-Header      /tmp/test.md    /^## Sub-Header$/;"     s       line:3  section:Header
Sub-Sub-Header  /tmp/test.md    /^### Sub-Sub-Header$/;"        s       line:11 section:HeaderSub-Header
Sub-Sub-Header  /tmp/test.md    /^### Sub-Sub-Header$/;"        s       line:5  section:HeaderSub-Header
Sub-Sub-Header  /tmp/test.md    /^#### Sub-Sub-Header$/;"       s       line:7  section:HeaderSub-HeaderSub-Sub-Header
Sub-Sub-Header  /tmp/test.md    /^#### Sub-Sub-Header$/;"       s       line:9  section:HeaderSub-HeaderSub-Sub-Header
```

Changing the `--sro` doesn't change a thing. But yes, I'm using UTF-8 in my `init.vim`. :thinking:

**Comment by jszakmeister** [comment]
I don't see the `»` or a `|` in the data that you pasted... so something seems off here.

And my apologies, you need to change `--sro` and the `'sro'` key in the TagBar configuration so that it knows how to split the nested elements.

**Comment by weilbith** [comment]
It works not if I set the pipe character into quotes (`--sro "|"`). Thank you very much for your help!

**Comment by jszakmeister** [comment]
> It works not if I set the pipe character into quotes (`--sro "|"`). Thank you very much for your help!

Right... `|` is a shell character, so you need to protect it.  You can also leave the option off entirely as markdown2ctags defaults to using the pipe character. :-)

Glad you got it working!

**Comment by weilbith** [comment]
> Right... | is a shell character, so you need to protect it.

Yeah, just wanted to mention it here in case someone find this issue having the same problem. :+1:
