### ISSUE TITLE
header levels bellow lower than the second are not shown and mess up the view 

### ISSUE THREAD

**Issue by kraxli** [jszakmeister/markdown2ctags#14]
I have headers below level to (so `### header level 3` or even `#### header level 4`. These levels are not shown in the right hierarchy but  appear somehow on the top (or something else messy is shown at the top having these levels in)

**Comment by jszakmeister** [comment]
Do you have an example document showing the problem?  My `test-docs/example.md` has a level 4 heading and it shows up just fine in TagBar.

Also, please include the output of running the tool directly, such as:

```text
:: ./markdown2ctags.py -f - --sort=yes test-docs/example.md
!_TAG_FILE_FORMAT	2
!_TAG_FILE_SORTED	1
Heading 1b	test-docs/example.md	/^Heading 1b$/;"	s	line:44
Heading 2	test-docs/example.md	/^Heading 2$/;"	s	line:1
Heading 2a	test-docs/example.md	/^## Heading 2a$/;"	s	line:14	section:\Heading 1
Heading 2b	test-docs/example.md	/^## Heading 2b$/;"	s	line:24	section:\Heading 1
Heading 2c	test-docs/example.md	/^## Heading 2c$/;"	s	line:29	section:\Heading 1
Heading 2d	test-docs/example.md	/^## Heading 2d$/;"	s	line:39	section:\Heading 1
Heading 2e	test-docs/example.md	/^Heading 2e$/;"	s	line:56	section:Heading 1b
Heading 3	test-docs/example.md	/^### Heading 3$/;"	s	line:19	section:\Heading 1|Heading 2a
Heading 4	test-docs/example.md	/^#### Heading 4$/;"	s	line:34	section:\Heading 1|Heading 2c
\Heading 1	test-docs/example.md	/^# \\Heading 1 ####$/;"	s	line:4
```

I believe this might be related more to your TagBar settings than an error in markdown2ctags though.

**Comment by kraxli** [comment]
thanks for coming back on this! 

My test.md file looks like:
```markdown
# Header 1 - L1
- a list item
- another list item

# Header 2 - L1
## header 2.1 - L2
- xxx
- yyy

### header 2.1.2
KADSFADSF
ASDFASDF


## header 2.2 - L2
ASDFAS

- asdf
- asdf

# Header 3 - L1
```
running  `./markdown2ctags.py -f - --sort=yes test.md ` produces

```bash
!_TAG_FILE_FORMAT	2
!_TAG_FILE_SORTED	1
Header 1 - L1	test.md	/^# Header 1 - L1$/;"	s	line:2
Header 2 - L1	test.md	/^# Header 2 - L1$/;"	s	line:6
Header 3 - L1	test.md	/^# Header 3 - L1$/;"	s	line:22
header 2.1 - L2	test.md	/^## header 2.1 - L2$/;"	s	line:7	section:Header 2 - L1
header 2.1.2	test.md	/^### header 2.1.2$/;"	s	line:11	section:Header 2 - L1|header 2.1 - L2
header 2.2 - L2	test.md	/^## header 2.2 - L2$/;"	s	line:16	section:Header 2 - L1
```
This output looks pretty good. However what I see in neovim is:
![image](https://user-images.githubusercontent.com/8371948/49965928-e02dcd80-ff1e-11e8-946e-295f738ab27c.png)

The tagbar settings I have are 
```vim
let g:tagbar_width = 25

 let g:tagbar_type_markdown = {
            \ 'ctagstype': 'markdown',
            \ 'ctagsbin' :  'C:\ProgramData\Anaconda3-5.2.0\Scripts\markdown2ctags.exe',
            \ 'ctagsargs' : '-f - --sort=yes --sro=»',
            \ 'kinds' : [
                \ 's:sections',
                \ 'i:images'
            \ ],
            \ 'sro' : '»',
            \ 'kind2scope' : {
                \ 's' : 'section',
            \ },
            \ 'sort': 0,
        \ }
```

I am working on Windows7 with neovim 3.1 and installed markdown2ctags with pip (but I also tested the most recent version from this github-repo which produces the same result)

**Comment by jszakmeister** [comment]
Hmmm... I see this:

![tagbar](https://user-images.githubusercontent.com/448087/49966659-9f1dc500-feee-11e8-91da-34ce7e882260.png)

Can you try changing the tagbar configuration to remove the `--sro=»` and the `'sro': '»'` to `'sro': '|'`?

Perhaps there is something else going on here.  But it appears that something about your setup is not handling the `»` character well. :-(  By removing the `--sro` option we'll default it the pipe character (`|`) instead, which is a plain old ascii character instead of a UTF-8 one. :-)

**Comment by kraxli** [comment]
ha :-) that seems to do the trick - at least on Linux (where I had the same problem)

![screenshot from 2018-12-13 21-55-42](https://user-images.githubusercontent.com/8371948/49967018-f8ebb280-ff21-11e8-9635-5a42c139a7c4.png)

I've just checked (on Linux) if the file format `dos` was the problem. But it is not since converting it to `unix` does not help. 

Many thanks!!!

**Comment by jszakmeister** [comment]
I suspect there's a setting we're missing somewhere (maybe in Vim proper) and the UTF-8 character isn't being handled well.  But I'm happy that worked for you!

**Comment by jszakmeister** [comment]
Just curious... on what platform did you run into this problem?  Windows?  Linux?  macOS?  Also, what are the values of `encoding` and `termencoding`?  I'd like to be able to re-create the problem to understand what is going on... you're the second person to run into an issue and I'm almost sure it's a configuration-related issue.

**Comment by kraxli** [comment]
I tried it out on Windows 7 with the format `dos` along with `encoding=utf-8` and on Linux (Ubuntu) with the format `dos` and `unix` along with `termencoding=utf-8`. The issue has happened on both OSs with both file formats.

**Comment by jszakmeister** [comment]
Interesting.  I'd love to know what's different in my setup that I don't see the problem. :-(  It works fine for me on Windows, Linux, and macOS. :confused:

**Comment by kraxli** [comment]
Hmm it may be a setting in neovim ...

**Comment by m040601** [comment]
I can confirm this same issue (also related to https://github.com/jszakmeister/markdown2ctags/issues/13)

It's always either one of these variants:
- messed up headers, with the "bb"'s in the outline when you use the chevron for 'sro'
- sometimes headers dont' go "deep enough", only level 1 or 2
- split headers when you user the '|' pipe for 'sro'

On my ArchLinux x64 system with:

- linux
Linux  4.20.13-arch1-1-ARCH #1 SMP PREEMPT  x86_64 GNU/Linux

- neovim
NVIM v0.3.4
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser
Features: +acl +iconv +jemalloc +tui 

- python
Python 3.7.2 and Python2 2.7.15

 - the script markdown2ctag..py
is automatically installed through the AUR package manager to /usr/bin/markdown2ctags,
https://aur.archlinux.org/packages/markdown2ctags/
they pull from the github the latest version, so it's fresh 


I have tryed many variations of removing, quoting and symbols,  with the two 'sro' lines:
-  'ctagsargs' : '-f - --sort=yes --sro=XYZ',
-  'sro' : XYZ,

My observations and this is what works best for me:
- the chevron (also tried other exotic chars) doesnt work, always causes the 'bb's issue
-  line, 'ctagsargs' : '-f - --sort=yes --sro="I"'
'sro' has to be there, and has to be extra double quoted
-  line, 'sro' : '|'
extra double quoting makes no difference

This will of course break outline headers containing the 'pipe'.
I edit a lot of markdown with links and I use them for markdown  headers.
A great deal websites use the 'pipe' in their page title schema, like for example,
"PAGE TITLE" | "SITE TITLE"
Building Fast Interpreters in Rust | Hacker News
https://news.ycombinator.com/item?id=19302262


Other than that, thank you so much for your script, and the care in maintaining it. Togethe with tagbar it's so useful

**Comment by jszakmeister** [comment]
@m040601 

Some of what you're saying doesn't make sense to me.  The chevron I can see being a problem.  My best guess is that there is some sort of encoding issue happening in vim/neovim, but I'm not seeing it and I've been unable to reproduce the issue. :-(  If you have a minimal vim configuration that can reproduce the problem, I'd be interested in seeing it--but it has to be minimal.

For the ctagsargs line, the pipe symbol itself does need to be quoted since it's a shell character but it the `--sro` option does *not* need to be there (so you can leave off the `--sro="|"`).  Since the option was introduced it has been optional.  You do, however, need the sro key in the rest of the tagbar configuration.  That's not for my tool, that's for Tagbar to know how to split.

Anything that you guys can share would be helpful.  And thank you for the kind words!  I'm glad you're enjoying the tool. :-)

**Comment by jszakmeister** [comment]
FWIW, these are my settings:

```
" Support for markdown, if available.
if executable("markdown2ctags")
    let g:markdown2ctags = 'markdown2ctags'
else
    let g:markdown2ctags = $VIMFILES . '/tool/markdown2ctags/markdown2ctags.py'
endif

" Local tagbar settings.  Assign g:tagbar_type_markdown to this value to enable
" support for markdown files in tagbar.
let g:local_tagbar_type_markdown = {
        \ 'ctagstype': 'markdown',
        \ 'ctagsbin' : g:markdown2ctags,
        \ 'ctagsargs' : '-f - --sort=yes --sro=»',
        \ 'kinds' : [
        \ 's:sections',
        \ 'i:images'
        \ ],
        \ 'sro' : '»',
        \ 'kind2scope' : {
        \ 's' : 'section',
        \ },
        \ 'sort': 0,
        \ }

" Enable support for markdown files in tagbar by default.  Disable if desired in
" your |VIMRC_AFTER| file via:
"   unlet g:tagbar_type_markdown.
let g:tagbar_type_markdown = g:local_tagbar_type_markdown

```

**Comment by jszakmeister** [comment]
@kraxli I assume that since you were in Windows you were using cmd.exe as your "terminal", is that correct?  If so, what does the command `chcp` show?

@m040601 What locale is your system set for?  Are you using a UTF-8 encoding?

Thanks!
