### ISSUE TITLE
neovim

### ISSUE THREAD

**Issue by mvmx3** [jszakmeister/markdown2ctags#17]
Except markdonw, it works

![深度截图_dde-desktop_20200123122647](https://user-images.githubusercontent.com/52132505/72957055-181f6980-3ddd-11ea-8d34-244fd3780bb2.png)

![深度截图_dde-desktop_20200123122728](https://user-images.githubusercontent.com/52132505/72957059-1bb2f080-3ddd-11ea-814f-2ac058a2a104.png)

![深度截图_dde-desktop_20200123123507](https://user-images.githubusercontent.com/52132505/72957062-1d7cb400-3ddd-11ea-9254-229ec1c5230f.png)

**Comment by jszakmeister** [comment]
Can you try my decode-args branch?  I believe it's because markdown2ctags is being installed under Python2 and I have to manually decode the arguments into unicode strings.

**Comment by mvmx3** [comment]
Sorry, what should I do ?  I don't understand that you said. What I use now is   https://github.com/jszakmeister/markdown2ctags/tree/better-enc-handling.

**Comment by jszakmeister** [comment]
Please try https://github.com/jszakmeister/markdown2ctags/tree/decode-args.  It has everything the better-enc-handling does, plus these extra couple of fixes.  Note: it'll end up on master, if things work for you as expected.

**Comment by mvmx3** [comment]
![深度截图_google-chrome_20200123181528](https://user-images.githubusercontent.com/52132505/72975791-5c762e00-3e0c-11ea-941f-6dd4e40594e7.png)

It don't works.

**Comment by jszakmeister** [comment]
Can you open tagbar and type `:messages`?  What is the output?

**Comment by jszakmeister** [comment]
This is what I'm getting with Neovim:
<img width="1331" alt="Screen Shot 2020-01-23 at 5 21 31 AM" src="https://user-images.githubusercontent.com/448087/72976272-49c60f80-3da0-11ea-94ca-589a7c8b6783.png">

**Comment by mvmx3** [comment]
It's no reaction when I  type  :messages  in neovim .

**Comment by mvmx3** [comment]
![深度截图_deepin-system-monitor_20200123184234](https://user-images.githubusercontent.com/52132505/72977761-2470ea00-3e10-11ea-8a24-3df67f5f0295.png)

**Comment by jszakmeister** [comment]
When things fail, I see something like this:
<img width="1329" alt="Screen Shot 2020-01-23 at 5 41 52 AM" src="https://user-images.githubusercontent.com/448087/72977726-1933a500-3da3-11ea-9674-230aa3c53b08.png">

The only other choice is to try to run markdown2ctags directly and see what's going on:

```
markdown2ctags -f - --sort=yes --sro=» path/to/file.md
```

For instance, I can do:
```
:: markdown2ctags -f - --sort=yes --sro=» test-docs/user-doc.md
!_TAG_FILE_ENCODING	utf-8
!_TAG_FILE_FORMAT	2
!_TAG_FILE_SORTED	1
0. 四个例子	test-docs/user-doc.md	/^## 0. 四个例子$/;"	s	line:3	section:Javascript
1. 变量数据类型	test-docs/user-doc.md	/^## 1. 变量数据类型$/;"	s	line:7	section:Javascript
2. 语句	test-docs/user-doc.md	/^## 2. 语句$/;"	s	line:9	section:Javascript
3. 正则	test-docs/user-doc.md	/^## 3. 正则$/;"	s	line:12	section:Javascript
4. 异常	test-docs/user-doc.md	/^## 4. 异常$/;"	s	line:14	section:Javascript
5. 表单	test-docs/user-doc.md	/^## 5. 表单$/;"	s	line:16	section:Javascript
6. 包	test-docs/user-doc.md	/^## 6. 包$/;"	s	line:18	section:Javascript
7. affaf	test-docs/user-doc.md	/^## 7. affaf$/;"	s	line:20	section:Javascript
A. 子	test-docs/user-doc.md	/^### A. 子$/;"	s	line:5	section:Javascript»0. 四个例子
Javascript	test-docs/user-doc.md	/^# Javascript$/;"	s	line:1
```

In the case of an error, it'd look more like this:
```
:: markdown2ctags -f - --sort=yes --sro=» test-docs/user-doc.md
Traceback (most recent call last):
  File "/Users/jszakmeister/.virtualenvs/markdown2ctags-py2/bin/markdown2ctags", line 11, in <module>
    load_entry_point('markdown2ctags', 'console_scripts', 'markdown2ctags')()
  File "/Users/jszakmeister/projects/jszakmeister/markdown2ctags/markdown2ctags.py", line 354, in cli_main
    main()
  File "/Users/jszakmeister/projects/jszakmeister/markdown2ctags/markdown2ctags.py", line 345, in main
    sectionsToTags(sections, options.sro),
  File "/Users/jszakmeister/projects/jszakmeister/markdown2ctags/markdown2ctags.py", line 274, in sectionsToTags
    tags.append(Tag.section(section, sro))
  File "/Users/jszakmeister/projects/jszakmeister/markdown2ctags/markdown2ctags.py", line 163, in section
    t.addField('section', sro.join(parents))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 0: ordinal not in range(128)
```

**Comment by mvmx3** [comment]
It's that.

![深度截图_deepin-system-monitor_20200123185235](https://user-images.githubusercontent.com/52132505/72978503-8aaa3c80-3e11-11ea-8215-cb8a8fc802b3.png)

**Comment by jszakmeister** [comment]
Something isn't right here--the _TAG_FILE_ENCODING field is missing.  It doesn't look like you have the right version of markdown2ctags installed.

**Comment by jszakmeister** [comment]
(at least, you're not using the branch)

**Comment by mvmx3** [comment]
![深度截图_google-chrome_20200123192047](https://user-images.githubusercontent.com/52132505/72980477-9dbf0b80-3e15-11ea-89d1-d31e64300900.png)

**Comment by mvmx3** [comment]
My computer has vim and neovim . vim works with markdown but neovim not works with markdown

**Comment by mvmx3** [comment]
![深度截图_google-chrome_20200123193323](https://user-images.githubusercontent.com/52132505/72981213-3b670a80-3e17-11ea-9519-f74b864c1103.png)

**Comment by jszakmeister** [comment]
Did you fix your tagbar configuration to use the correct markdown2ctags?

**Comment by mvmx3** [comment]
yes, I fix the path of markdown2ctags, the path is true because of the path hinting.

![深度截图_google-chrome_20200123203002](https://user-images.githubusercontent.com/52132505/72984671-3f972600-3e1f-11ea-8669-3666433fab24.png)

**Comment by mvmx3** [comment]
![深度截图_google-chrome_20200123203202](https://user-images.githubusercontent.com/52132505/72984783-6fdec480-3e1f-11ea-99a1-f54d21b556ec.png)

**Comment by jszakmeister** [comment]
:messages is still empty?

**Comment by mvmx3** [comment]
Yes, it is empty still

**Comment by jszakmeister** [comment]
Can I have a copy of the file this fails on?  Do you mind putting it on [Gist](https://gist.github.com/) and sending me the link?  Or copying the text into this issue and providing me the same filename that you are using?

**Comment by mvmx3** [comment]
[cv.txt](https://github.com/jszakmeister/markdown2ctags/files/4107651/cv.txt)

rename .txt to .md

**Comment by jszakmeister** [comment]
It works for me with Neovim. :-(
<img width="936" alt="Screen Shot 2020-01-24 at 6 19 01 AM" src="https://user-images.githubusercontent.com/448087/73065425-87df3400-3e71-11ea-9df5-909794791a32.png">

**Comment by jszakmeister** [comment]
Without some other piece of information here, I don't think I can help.  I did release a new version of markdown2ctags with all the unicode bits in there, so you can use that or run from master again.  I believe it likely fixes the issue you are seeing.  I'm closing this issue.  If you turn up something more (error output from markdown2ctags, a file that fails from the command line, etc.), please open a new issue (or re-open this one, if it's related to neovim) and I'll take a look.  At this point, I don't feel there is anything more that I can do right now.
