### ISSUE TITLE
nothing is shown in the tagbar window after update the plugin

### ISSUE THREAD

**Issue by yujiangang** [jszakmeister/markdown2ctags#18]
It works well before I update the plugin. However nothing is shown in the tagbar window after I update the plugin today.

**Comment by jszakmeister** [comment]
You'll have to offer more than that.  Do you have a sample file where this does not work?

**Comment by jszakmeister** [comment]
@yujiangang Also, have you tried running the tool directly, such as `markdown2ctags -f - path/to/some-document.md`?  What version of Python did you use, and under what operating system?  I definitely need some details here.  I'm running with this every day, and it appears to be quite fine.  So I need some details from your end if we're to fix the issue.  My guess is that there is something environmental going on and not necessarily the tool at fault.

**Comment by yujiangang** [comment]
@jszakmeister Thanks for your reply!

I am using Python 2.7.17. I get the same results on both Ubuntu and openSUSE systems. The markdown2ctags tool doesn't work for all the markdown files somehow.  I tried `markdown2ctags -f - test.md`.  I got the following information.

```
!_TAG_FILE_ENCODING     utf-8   //
!_TAG_FILE_FORMAT       2       //
!_TAG_FILE_SORTED       1       //
OpenSSH Server  test.md        /^OpenSSH Server$/;"    s       line:3
```
The test files is:

```
OpenSSH Server
--------------

  remote connection to my laptop via ssh

  Short version:

  ```bash
  $ ssh-keygen -t rsa -f output_keyfile # on my laptop (client)
  $ vim ~/.ssh/config
  $ ssh-copy-id -i /path/to/output_keyfile.pub SERVERNAME # (from my laptop (client) to remote server)
  $ chmod 700 .ssh/
  ```
```

**Comment by jszakmeister** [comment]
@yujiangang So that output looks good, and markdown2ctags seems to be working as it should for `test.md`.  Do you have an example where it does not work?

**Comment by yujiangang** [comment]
@jszakmeister Actually, Markdown2ctags doesn't work as expected for test.md. The tags are not shown in the right tagbar window in the flowing picture somehow. The results are the same for other markdown files.

![test](https://user-images.githubusercontent.com/20054160/98227050-1af7df00-1f57-11eb-96d8-c5570fc730c4.png)

**Comment by jszakmeister** [comment]
I get that, but running the tool directly is producing the correct output.
I also took what you posted, dropped it into a file, and was able to the
the tags.  So there's something else happening.  Either the file you posted
is not really representative of what's in there, or there is some sort of
misconfiguration. But given the file you posted, and the results of running
directly, it's markdown2ctags is working correctly.

**Comment by yujiangang** [comment]
@jszakmeister That's weird. I even tried to reinstall everything. Still, nothing is shown in the tagbar.

**Comment by jszakmeister** [comment]
@yujiangang Can you put the actual file in a Gist (https://gist.github.com/) and post the link here?  Sometimes trying to include it the content of a ticket can "fix" some encoding issues, and we don't want that to happen.  Also, what is your tagbar configuraton?  It smells like a configuration or environment error, especially since running it directly works as expected.

**Comment by jszakmeister** [comment]
FYI, here are the settings I'm using:

```vim
let g:tagbar_type_markdown = {
        \ 'ctagstype': 'markdown',
        \ 'ctagsbin' : 'markdown2ctags',
        \ 'ctagsargs' : '-f - --sort=yes --sro=»',
        \ 'kinds' : [
        \ 's:sections',
        \ 'i:images'
        \ ],
        \ 'sro' : '»',
        \ 'kind2scope' : {
        \ 's' : 'section',
        \ },
        \ 'sort': 0,
        \ }
```

**Comment by yujiangang** [comment]
@jszakmeister The test.md file is ok. I've put it on the gist. Here is the link: https://gist.github.com/yujiangang/8cccff782829cdd31e44d437aff69ad8. I use the same settings as yours. The problem is related to the ubuntu system. I worked on the ubuntu system during the past few days. The same problem happens when I log in to the openSUSE system via ssh on the ubuntu system. The Markdown2ctags works when I log in to the openSUSE system this morning. The configurations are the same for both systems. I also tried to create a new user on the Ubuntu system and install all the tools from scratch. It doesn't work too.

**Comment by jszakmeister** [comment]
@yujiangang I'm not sure I'm following what you're saying.  On my macOS system, everything looks good:
![image](https://user-images.githubusercontent.com/448087/98609604-a062f280-22bb-11eb-9dca-dcdbff9c8197.png)

Have you tried running markdown2ctags from the command line on the system that doesn't work?  How are you installing markdown2ctags?  Via pip?  Just copying the script?  Which Ubuntu version?  This really smells like an environment problem, rather than an issue with markdown2ctags, but I bet it's something silly.

**Comment by yujiangang** [comment]
@jszakmeister Problem is solved. It works after I install markdown2ctags via pip. I just copied the script using vbundle plugin in .vimrc before. Then I used markdown2ctags.py directly. The script works on openSUSE and also worked on the Ubuntu system before. I tried on both Ubuntu 18.04 LTS and 20.04 LTS. The script doesn't work directly anymore now. I installed the markdown2ctags via pip this morning thanks to your reply. Then it works perfectly. It is really silly. Thanks again for your help!

**Comment by jszakmeister** [comment]
I'm actually certain it does work directly. :-)  A friend and I bundle into our vim configuration here: https://github.com/drmikehenry/vimfiles/blob/master/tool/markdown2ctags/markdown2ctags.py.  My suspicion is that "python" isn't available (at least, not under that name).  So when trying to run it directly, the shebang line ("/usr/bin/env python") fails to find python and it just fails.  I'm tempted to make it "python3", but I work with enough legacy systems right now where that's not a great choice.  Installing via pip is definitely the best way, but if you ever use the script directly again, you might need to modify that line so a suitable python executable is found.  Glad it's working for you though!

**Comment by yujiangang** [comment]
@jszakmeister You are right. It is a problem with "/usr/bin/env python". But I've tried to change it to  "/usr/bin/env python2" several days ago. It worked when I tried `markdown2ctags.py -f - test.md`. However it didn't work in the vim tagbar window. I just tested to use the script directly by making it to "/usr/bin/env python3". Then the script works directly in the vim tagbar window.
